export const SettingTexts = {
  vista: "Vista",
  dashboard: "Dashboard",
  logOut: "Log Out",
  settings: "Settings",
  subTitle: "Plan and manage your gatherings effortlessly.",
  navBarName: "Olivia Rhye",
  filters: "Filters",
  free: "Free",
  paid: "Paid",
  inviteUser: "Invite user",
  inviteFirst: "Invite your first user",
  addUsers: "Add users on this page",
  allEvent: "All events",
  email: "ekumkofi@example.com",
  personalInfo: "Personal Info",
  updatePhoto: "Update your photo and personal details.",
  firstNameLabel: "First Name",
  lastNameLabel: "Last Name",
  emailLabel: "Email",
  clickToUpload: "Click to upload",
  dragDrop: "or drag and drop",
  imageSpec: "SVG, PNG, JPG or GIF (max. 800x400px)",
  cancel: "Cancel",
  saveChanges: "Save Changes"
};

export const settingImages = {
  orgDasImg: "assets/esp/logo.png",
  dashboardChartImg: "assets/esp/dashboard/bar-chart-square-02.png",
  eventLayerImg: "assets/esp/dashboard/layers-three-01.png",
  settingsImg: "assets/esp/dashboard/user.png",
  logoutImg: "assets/esp/dashboard/logout.png",
  navbarBell: "assets/esp/dashboard/bell.png",
  navBarImg: "assets/esp/dashboard/avatar.png",
  navBarDownArrow: "assets/esp/dashboard/down.png",
  cardImg: "assets/esp/dashboard/event-created.png",
  searchImg: "assets/esp/dashboard/search.png",
  filterImg: "assets/esp/dashboard/filter.png",
  userPlus: "assets/esp/dashboard/user-plus.png",
  accountSetting: "assets/esp/dashboard/settings.png",
  uploadImg: "assets/esp/dashboard/upload.png",

};
