
export const dashboardConstant = {
    orgDasImg: 'assets/esp/logo.png',
    dashBoardChartImg: 'assets/esp/dashboard/bar-chart-square-02.png',
    eventLayerImg: 'assets/esp/dashboard/layers-three-01.png',
    settingsImg: 'assets/esp/dashboard/user.png',
    logoutImg: 'assets/esp/dashboard/logout.png',
    navbarBell: 'assets/esp/dashboard/bell.png',
    navBarImg: 'assets/esp/dashboard/avatar.png',
    navBarDownArrow: 'assets/esp/dashboard/down.png',
    cardImg: 'assets/esp/dashboard/three-dots.png',
    baseImg: 'assets/esp/dashboard/base.png',
    pieChart: 'assets/esp/dashboard/pie_chart.png',
    
    profileImageUrl: '',
    fullName: sessionStorage.getItem('organizerName') || '',
    NavBarName: sessionStorage.getItem('organizerName') || '',
    subTitle: 'Plan and manage your gatherings effortlessly.',
    Dashboard: 'Dashboard',
    Users: 'Users',
    LogOut: 'Log out',
    eventCreated: 'Events created',
    revenue: 'Revenue',
    fourThousand: 4000,
    Attendees: 'Number of Attendees',
    EightThousand: 8000,
    RevChart: 'Revenue chart',
    totalEvents: 0,
    totalTickets: 0,
    totalRevenue: 0,
    organizerPercentage: 0,
    ticketSoldPercentage: 0,
    activeStep: 'monthly',
    showProfileCard: false,
    value: new Date(),
    email: 'ekumkofi@example.com',
    
    ticketsSoldContent: "Stay ahead of the curve with our real-time 'Tickets Sold Today' tracker, offering immediate insights into today's ticket sales. By keeping a pulse on current sales trends, you'll be equipped to make proactive decisions and fine-tune event strategies for optimal success."
};
